name: pollsam
description: Ein REST-Server, der Anforderungen von Projekt POLLECTOR beantwortet.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  args: ^2.1.0
  path: ^1.8.0
  http: ^0.13.0
  dart_bones: "^1.2.2"
  sprintf: ^6.0.0
  #  path: ../../dart/dart_bones

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  #mockito: ^4.1.4
  #test_coverage: ^0.5.0
